Fix sidebar height & hide ScrollUpButton until scrolled (fade in)
gotify/server pull request #384
Opened 2021-01-22 04:42 UTC by StewartThomson

Fixes #383 and issue found within #276

2021-01-22 17:20 UTC, jmattheis requested changes
Thanks for your contribution. This actually has been bugging me too.

I've added remarks in subcomments.

2021-01-22 17:20 UTC, jmattheis commented on ui/src/common/ScrollUpButton.tsx
> +            window.addEventListener('scroll', () => {
The handler probably should be removed on https://reactjs.org/docs/react-component.html#componentwillunmount

2021-01-22 17:20 UTC, jmattheis commented on ui/src/common/ScrollUpButton.tsx
> +                    display: `${this.state.display}`,
```suggestion
                    display: this.state.display,
```

2021-01-22 17:20 UTC, jmattheis commented on ui/src/common/ScrollUpButton.tsx
> +                    this.setState({opacity: currentScrollPos / 500});
Could you merge the 2 setStates into one? Same for the one below
```suggestion
                    this.setState({opacity: currentScrollPos / 500, opacity: Math.min(currentScrollPos / 500, 1)});
```
Also added Math.min that opacity doesn't exceed 1.

2021-01-22 17:21 UTC, jmattheis commented on ui/src/common/ScrollUpButton.tsx
> +                    this.setState({opacity: currentScrollPos / 500});
Could you merge the 2 setStates into one? Same for the one below
```suggestion
                    this.setState({opacity: currentScrollPos / 500, opacity: Math.min(currentScrollPos / 500, 1)});
```
Also added Math.min that opacity doesn't exceed 1.

2021-01-22 21:40 UTC, StewartThomson commented
Feedback implemented @jmattheis

2021-01-24 19:03 UTC, jmattheis commented on ui/src/common/ScrollUpButton.tsx
> +            window.removeEventListener('scroll', this.scrollHandler.bind(this));
I think this doesn't work as .bind will give a new reference and thus, doesn't unregister the old handler. I'll fix this. Also, I'll prevent some rerenders, by checking if the state will be changed.

2021-01-24 19:58 UTC, jmattheis approved these changes

2021-01-24 19:58 UTC, merged