Added Different notification color for priority
gotify/server pull request #516
Opened 2022-10-10 20:56 UTC by Tert0

Closes #269 

Implemented different colors for message borders, which are based on the message priority.

![image](https://user-images.githubusercontent.com/62036464/194950732-02462da6-eae6-47f5-a676-28ce9bbc5251.png)

**Note:**
I'll try to implement this to [gotify/android](https://github.com/gotify/android)

2022-10-15 18:55 UTC, jmattheis requested changes
thanks for your contribution, I've added remarks in sub comments

2022-10-15 18:55 UTC, jmattheis commented on config/config.go
> +	PriorityColors    []struct {
I don't think this needs to be configurable. We can hardcode the colors. i think something like this as border color should be enough:
```
rgba(243, 156, 18, Math.min(1, msg.priority/10))
```

2022-10-15 18:55 UTC, jmattheis commented on api/application.go
> +// # Params allowed to create or update Applications
Please revert all the backend changes related to golint, this should be done in a separate PR.

2022-10-21 18:42 UTC, jmattheis approved these changes
Thanks, I've changed the colors a little bit, so that messages are colored orange for medium priority.

2022-10-21 18:50 UTC, merged

2022-10-21 22:24 UTC, Tert0 commented
Could you please label this PR as `hacktoberfest-accepted`?